#ifndef BUG_H_GENERATED_
#define BUG_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'env' '__cxa_rethrow' */
extern void (*Z_envZ___cxa_rethrowZ_vv)(void);
/* import: 'env' '__sys_stat64' */
extern u32 (*Z_envZ___sys_stat64Z_iii)(u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_close' */
extern u32 (*Z_wasi_snapshot_preview1Z_fd_closeZ_ii)(u32);
/* import: 'wasi_snapshot_preview1' 'fd_read' */
extern u32 (*Z_wasi_snapshot_preview1Z_fd_readZ_iiiii)(u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_seek' */
extern u32 (*Z_wasi_snapshot_preview1Z_fd_seekZ_iijii)(u32, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_write' */
extern u32 (*Z_wasi_snapshot_preview1Z_fd_writeZ_iiiii)(u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_fd_fdstat_getZ_iii)(u32, u32);
/* import: 'wasi_snapshot_preview1' 'environ_sizes_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_environ_sizes_getZ_iii)(u32, u32);
/* import: 'wasi_snapshot_preview1' 'environ_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_environ_getZ_iii)(u32, u32);
/* import: 'env' '__sys_readlink' */
extern u32 (*Z_envZ___sys_readlinkZ_iiii)(u32, u32, u32);
/* import: 'env' '__sys_fstat64' */
extern u32 (*Z_envZ___sys_fstat64Z_iii)(u32, u32);
/* import: 'env' '__sys_lstat64' */
extern u32 (*Z_envZ___sys_lstat64Z_iii)(u32, u32);
/* import: 'env' '__sys_mkdir' */
extern u32 (*Z_envZ___sys_mkdirZ_iii)(u32, u32);
/* import: 'env' '__sys_fchmod' */
extern u32 (*Z_envZ___sys_fchmodZ_iii)(u32, u32);
/* import: 'env' '__sys_chmod' */
extern u32 (*Z_envZ___sys_chmodZ_iii)(u32, u32);
/* import: 'env' '__sys_ftruncate64' */
extern u32 (*Z_envZ___sys_ftruncate64Z_iiiii)(u32, u32, u32, u32);
/* import: 'env' '__sys_getcwd' */
extern u32 (*Z_envZ___sys_getcwdZ_iii)(u32, u32);
/* import: 'env' '__sys_unlink' */
extern u32 (*Z_envZ___sys_unlinkZ_ii)(u32);
/* import: 'env' '__sys_rmdir' */
extern u32 (*Z_envZ___sys_rmdirZ_ii)(u32);
/* import: 'env' '__sys_rename' */
extern u32 (*Z_envZ___sys_renameZ_iii)(u32, u32);
/* import: 'env' '__sys_getdents64' */
extern u32 (*Z_envZ___sys_getdents64Z_iiii)(u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'proc_exit' */
extern void (*Z_wasi_snapshot_preview1Z_proc_exitZ_vi)(u32);
/* import: 'env' 'emscripten_notify_memory_growth' */
extern void (*Z_envZ_emscripten_notify_memory_growthZ_vi)(u32);
/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_args_sizes_getZ_iii)(u32, u32);
/* import: 'wasi_snapshot_preview1' 'args_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_args_getZ_iii)(u32, u32);
/* import: 'wasi_snapshot_preview1' 'clock_time_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_clock_time_getZ_iiji)(u32, u64, u32);

/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: '__indirect_function_table' */
extern wasm_rt_table_t (*WASM_RT_ADD_PREFIX(Z___indirect_function_table));
/* export: 'malloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_mallocZ_ii))(u32);
/* export: 'main' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_mainZ_iii))(u32, u32);
/* export: '_start' */
extern void (*WASM_RT_ADD_PREFIX(Z__startZ_vv))(void);
/* export: '__errno_location' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___errno_locationZ_iv))(void);
/* export: 'fflush' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_fflushZ_ii))(u32);
/* export: 'stackSave' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_stackSaveZ_iv))(void);
/* export: 'stackRestore' */
extern void (*WASM_RT_ADD_PREFIX(Z_stackRestoreZ_vi))(u32);
/* export: 'stackAlloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_stackAllocZ_ii))(u32);
/* export: 'emscripten_stack_init' */
extern void (*WASM_RT_ADD_PREFIX(Z_emscripten_stack_initZ_vv))(void);
/* export: 'emscripten_stack_get_free' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_emscripten_stack_get_freeZ_iv))(void);
/* export: 'emscripten_stack_get_end' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_emscripten_stack_get_endZ_iv))(void);
#ifdef __cplusplus
}
#endif

#endif  /* BUG_H_GENERATED_ */
